### ISSUE TITLE
Descrizione breve progetto

### ISSUE THREAD

**Issue by aborruso** [ondata/i-dati-che-vorrei#12]
Caro @davidedelmonte , la scrive una frase di descrizione breve del progetto?

Per intenderci è quella che sarà leggibile nella condivisione social e nei motori di ricerca.

Grazie

**Comment by davidedelmonte** [comment]
ipotesi1: perché, come e quali dati vogliamo
ipotesi2: quali dati vogliamo, come e perché
ipotesi3: liberiamo i dati del PNRR
ipotesi3b: aiutaci a liberare i dati del PNRR
ipotesi4: dati aperti per una società aperta
ipotesi5: chiedi i dati del PNRR insieme a noi

**Comment by pcmasuzzo** [comment]
Mi piace molto la 4: **dati aperti per una società aperta**; generica, non dice PNRR, ma credo che si sposi bene con il respiro ampio di quello che stiamo facendo.
Se ci sono più caratteri a disposizione potremmo anche scrivere:
**dati aperta per la trasparenza, partecipazione, collaborazione**

**Comment by pcmasuzzo** [comment]
Non usiamo *dati aperta per la trasparenza, partecipazione, collaborazione*, mi son pentita. Questa dicitura vista e rivista ha perso un po' il senso.

Perché non scriviamo: **apriamo i dati per progettare una società più giusta, inclusiva, collaborativa.**
Userei qualche parola chiave del documento. Detto ciò, lascio a voi :)

**Comment by aborruso** [comment]
> Perché non scriviamo: **apriamo i dati per progettare una società più giusta, inclusiva, collaborativa.**
> Userei qualche parola chiave del documento. Detto ciò, lascio a voi :)

Ecco questo mi piace! Che dici @davidedelmonte ?

**Comment by aborruso** [comment]
@pcmasuzzo @davidedelmonte dopo confronto in cabina di regia, piccola modifica in: apriamo i dati **del PNRR** per progettare una società più giusta, inclusiva, collaborativa.

Il messaggio è di senso largo, ma il progetto nasce per spingere sul PNRR
