### ISSUE TITLE
Fare glossario

### ISSUE THREAD

**Issue by pcmasuzzo** [ondata/i-dati-che-vorrei#20]
Un bel glossario che spieghi i nomi/termini del documento che hanno bisogno di contesto, spiegazione

**Comment by aborruso** [comment]
@pcmasuzzo @davidedelmonte ho creato il glossario minimo del capitolo "Come li vorrei".

Lo trovate nel DOC. Per ora lavoriamo lì. Lo vado mettendo online.
Mi sta piacendo

**Comment by aborruso** [comment]
Ecco il glossario in utilizzo

![image](https://user-images.githubusercontent.com/30607/153705249-e21f7999-cae1-495d-aec2-7593f06162d6.png)
