### ISSUE TITLE
Scrivere testo benvenuto

### ISSUE THREAD

**Issue by aborruso** [ondata/i-dati-che-vorrei#8]

**Comment by davidedelmonte** [comment]
In attesa di conferma dopo cabina di regia (11/02/2022):

#DatiBeneComune è una campagna nata nel novembre 2020 per chiedere al Governo italiano di pubblicare in formato aperto e accessibile i dati sulla gestione della pandemia di COVID-19.

La campagna è stata accolta  sin dall’inizio con entusiasmo da parte di esperti, organizzazioni, testate giornalistiche, che hanno aderito immediatamente all’iniziativa. Ad oggi, oltre 250 organizzazioni si sono ufficialmente unite all’iniziativa e circa 55.000 cittadini e cittadine hanno firmato la petizione connessa.

Da maggio 2021, in collaborazione con l’Osservatorio Civico PNRR,  si chiede l’apertura di tutti i dati relativi al PNRR (Piano Nazionale di Ripresa e Resilienza) e, più in generale, l’apertura di tutti i dati di pubblico interesse.

I dati che vorrei, grazie all’intervento di autorevoli esperti ed esperte di diverse realtà della società civile, intende delineare le caratteristiche e le modalità di pubblicazione dei dati aperti del PNRR, in modo che le attività di monitoraggio civico siano rese possibili. 

La pubblicazione sarà arricchita nel tempo con ulteriori sezioni dedicate alle priorità trasversali riconosciute nel PNRR: i dati per misurare l’impatto sulle questioni di genere, quelle generazionali, e quelle territoriali.

#DatiBeneComune con questo documento chiede dunque che si passi finalmente dalla teoria alla pratica, dalle parole ai fatti, dalle buone intenzioni alla vera trasparenza e partecipazione. E con spirito costruttivo, collaborativo, partecipativo, suggerisce come farlo.
